### ISSUE TITLE
Nodekit examples doesn't work out of the box.

### ISSUE THREAD

**Issue by librewarrior** [small-tech/nodekit#6] opened 2022-03-11 21:18 UTC
I have just installed nodekit from the terminal. 

I try to run: 
`nodekit examples/simple-chat/index.page`

This leads to this error message:

SyntaxError: The requested module 'worker_threads' does not provide an export named 'BroadcastChannel'
    at ModuleJob._instantiate (internal/modules/esm/module_job.js:124:21)
    at async ModuleJob.run (internal/modules/esm/module_job.js:179:5)
    at async Loader.import (internal/modules/esm/loader.js:178:24)
    at async internal/process/esm_loader.js:57:9
    at async Object.loadESM (internal/process/esm_loader.js:67:5)

I'm using Ubuntu 20.04.4 LTS.

I have not yet tested out non-examples.

**Comment by aral** [comment] 2022-06-03 11:12
Hi @librewarrior, thanks for the report and apologies for the late reply. I was away for a bit and then working on a major refactor.

The examples should work out of the box in the current state (unless otherwise stated in the readme). But, again, things are moving fast and development is back in the main branch now so things might break depending on when you try them. Things should get steadier as I add more tests and development matures.

Regarding your error, I wonder if it was a Node version issue. I’ve recently bumped the minimum Node version required to 18+.

Thanks again; closing as cannot reproduce.

**Closed by aral** 2022-06-03 11:12 UTC
